title: So I'm starting an MMO
theme: minima
author: Bungara Hackmore
email: bengarahackmore@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 I played World of Warcraft for more than a decade. Then I discovered the Viera
# social links

show_excerpts: false # set to false to remove excerpts on the homepage
